### ISSUE TITLE
{: download} appears to fail to show in DYS0

### ISSUE THREAD

**Issue by aetomala** [ibm-cloud-docs/starters#1]
Hi I am an IBM internal and I dont know if this is the right place to place this issue.  This page appears to be served in a CIO dedicated environment DYS0.  This page offers the ability to download the code in the getting started page; However, this option is not available at all.  I think this is because in your MD file {: download} is stated rather than {:download}.  We need to show this on our getting started page and updating this page is important to us.  Thanks. if you need to contact me directly slack me or email me aetomala@us.ibm.com

**Comment by jenschlot** [comment]
Opened https://github.ibm.com/Bluemix/Bluemix-doc-framework/issues/1028

**Comment by cdmauney** [comment]
Addressed in issue mentioned above. Closing.
