### ISSUE TITLE
There are no instructions to download the application

### ISSUE THREAD

**Issue by powellquiring** [ibm-cloud-docs/starters#13]
After creating a nodejs app in cloud foundry the getting started page was titled: Download, modify, and redeploy your Cloud Foundry app with the command line interface.

https://github.com/IBM-Bluemix-Docs/starters/blob/master/install_cli.md

There are no instructions on how to download the app.  From my past experience this was possible and part of the normal introductory flow.  I'm not sure how to proceed from here to change the contents of the application provided as an example.

**Comment by uwefassnacht** [comment]
Same as https://github.com/IBM-Bluemix-Docs/starters/issues/5 and https://github.com/IBM-Bluemix-Docs/starters/issues/4

They've been open for 20 months now :-(

**Comment by cdmauney** [comment]
Link to download code is available:
![image](https://user-images.githubusercontent.com/22623884/88537305-4f184700-cfdb-11ea-9ba4-f2ba1bb40515.png)
