### ISSUE TITLE
getting started page starts with navigating to code directory

### ISSUE THREAD

**Issue by bro1** [ibm-cloud-docs/starters#2]
I would expect to first explain where to get the source code for application first.
Looking at the page history there is some indication that the text where to download application code from was on the page earlier. 

![image](https://user-images.githubusercontent.com/397284/28992509-53c6c8f4-79f2-11e7-8116-60c2a4b5c140.png)

**Comment by EunKyung-Kim** [comment]
So do I. I can't find download link at "Getting started" page. Document guides as follows. But, I can't follow step 2.

Download the application code by taking the following steps:

    1. At the Bluemix dashboard, click your application tile.
    2. Click the application tile to go to the overview page. Click Start Coding > Download Starter Code to download the starter application package.

**Comment by uwefassnacht** [comment]
Same here. The instructions make no sense. It's been like this for almost 2 months now :-(

**Comment by jenschlot** [comment]
Thanks for reporting the issue. We are working on a fix...

**Comment by tokida** [comment]
It is working in Sydney. (Nodejs cf application)

**Comment by tnakajo** [comment]
@jenschlot When do you fix? ETA?

This is from Bluemix support. I tested the node.js and the liberty java in all regions. All regions except Sydney having this issue as the getting started page uses this page (version 2017-06-31).

The getting started page in Sydney region uses the newer page (version 2017-09-13) from https://github.com/IBM-Bluemix-Docs/nodejs/blob/master/getting-started.md and https://github.com/IBM-Bluemix-Docs/liberty/blob/master/getting-started.md.  
Do you have any plan to switch to this page in the other regions?

**Comment by tnakajo** [comment]
@jenschlot I checked the page today but the issue still exists. Has the fix been delivered last Saturday really?

**Comment by tnakajo** [comment]
This is the dev defect: https://github.ibm.com/Bluemix/core-dev/issues/3923

**Comment by vbontempi** [comment]
Hello team, this is still an issue and it is totally incoherent with the documentation, suggesting to download and to change the source code.
Could be possible to have it fixed?

**Comment by tnakajo** [comment]
@vbontempi I am also expecting a fix. I keep following up on the dev defect: https://github.ibm.com/Bluemix/core-dev/issues/3923
Please add a comment in it.

**Comment by cdmauney** [comment]
Issue addressed. Closing.
