### ISSUE TITLE
Can't download starter files

### ISSUE THREAD

**Issue by abdulrab09** [ibm-cloud-docs/starters#4]
IBM website says Download, modify, and redeploy your Cloud Foundry app with the command line interface but there is no option in command line to download the application.

**Comment by amagard** [comment]
True, I am having the same problem. The step to initially download the code is missing.

**Comment by aa7955** [comment]
.... and it's January 2018 and it still isn't solved.

**Comment by nerdralph** [comment]
It looks like the code was at:
https://github.com/IBM-Bluemix/bluemix-python-flask
but didn't get moved to the IBM-Cloud repo when they shutdown the IBM-Bluemix repo.

This one is pretty close to the version of the code being used, but slightly out-of date:
https://github.com/whitfiea/bluemix-python-flask-sample

The boilerplate flask app routes / to 
```
def Welcome():
    return app.send_static_file('index.html')
```

I can ssh into the vm to see the files, but haven't figured out how to do a git pull or git clone of them.  If all else fails I'll tar up the files and copy them.

**Comment by nerdralph** [comment]
I found another repo that is pretty close to what is used for the cloud demo, so I forked and updated it.
https://github.com/nerdralph/Flask-Demo
