### ISSUE TITLE
[python-flask-boilerplate] Get HTTP 404 attempting to download starter code [Location: US South] 

### ISSUE THREAD

**Issue by bmdu1569** [ibm-cloud-docs/starters#6]
Location: `US South`
When you first create an app using the python-flask-boilerplate, you are brought to a page that allows you to download the starter code.
```
After you install the command line interface, you can get started:
Download the code for your app to a new directory to set up your development environment.

Download application code
```
When client tries to download code, get 404 error.

NOTE : this is _NOT_ reproducible if similar python-flask-boilerplate app deployed to `UK region` - able to download code successfully - why is this the case?
Do they not used the same git repo for the page?
Thanks

**Comment by bmdu1569** [comment]
@neal-timpe just wanted to check if this issue is reported to the right place? Thanks

**Comment by neal-timpe** [comment]
@bmdu1569 I see this and I'm working on finding the answer.

**Comment by bmdu1569** [comment]
Thanks @neal-timpe :)   have a good WE.

**Comment by bmdu1569** [comment]
hi again @neal-timpe, swinging back round to this, any idea if anything happened, or would you have a link to the core-dev repo where it was most recently reported. thanks

**Comment by neal-timpe** [comment]
@bmdu1569 There has been work on this. The developers thought they had it fixed with the last release, but the issue remains. I'll ping you the link to the internal issue.

**Comment by cdmauney** [comment]
Tested and was able to download code. 
![image](https://user-images.githubusercontent.com/22623884/88537983-94894400-cfdc-11ea-8fe9-dd8270ceaa98.png)
